image: maven:3-jdk-8

variables:
  MYSQL_DATABASE: "estore"
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

services:
  - mysql:latest  

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS package -DskipTests
  artifacts:
    paths:
      - target/eStore*.jar
#test:
#  stage: test
#  script:
#    - mvn pmd:pmd
#    - mvn pmd:cpd
#    - mvn test

package:
  stage: deploy
  script:
    - docker login -u estore-gitlab-ci -p $CI_TOKEN docker.uibk.ac.at:443
    - docker build -t docker.uibk.ac.at:443/csav4645/sq-estore ./target/*.war
    - docker push docker.uibk.ac.at:443/csav4645/sq-estore