image: maven:3-jdk-8

services:
  - mysql:latest

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  # Configure mysql environment variables (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: "estore"
  MYSQL_ROOT_PASSWORD: ""

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mysql -u root -p "" $MYSQL_DATABASE < src/test/java/resources/schema.sql
    - mysql -u root -p "" $MYSQL_DATABASE < src/test/java/resources/import.sql
    - mvn $MAVEN_CLI_OPTS clean install

test:
  stage: test
  script:
    - mvn pmd:pmd
    - mvn $MAVEN_CLI_OPTS test