image: maven:3-jdk-8

variables:
  MYSQL_DATABASE: "estore"
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

services:
  - mysql:latest  

build:
  stage: build
  script:
    - mvn package -DskipTests
  artifacts:
    paths:
      - target/eStore*.jar
test:
  stage: test
  script:
    - mvn pmd:pmd
    - mvn pmd:cpd
    - mvn test