image: maven:3-jdk-8

services:
  - mysql:latest

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  # Configure mysql environment variables (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: "estore"
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn graphwalker:generate-test-sources
    - mvn pmd:pmd
    - mvn test