image: maven:3-jdk-8

stages:
  - init
  - build
  - static-analytic
  - test

variables:
  MYSQL_DATABASE: "estore"
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

mysql-init:
  services:
    - mysql
  image: mysql
  stage: init
  script:
    - mysql -u root $MYSQL_DATABASE < src/test/resources/schema.sql
    - mysql -u root $MYSQL_DATABASE < src/test/resources/import.sql

build:
  stage: build
  script:
    - mvn package -DskipTests
  artifacts:
    paths:
      - target/eStore*.jar

PMD:
  stage: static-analytic
  script:
    - mvn pmd:pmd
    - mvn pmd:cpd

test:
  stage: test
  script:
    - mvn test