image: maven:3-jdk-8

variables:
  MYSQL_DATABASE: "estore"
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  
services:
  - mysql:latest  

build:
  stage: build
  script:
    - mvn compile -DskipTests

test:
  stage: test
  script:
    - mvn graphwalker:generate-test-sources
    - mvn pmd:pmd
    - mvn test

package:
  stage: deploy
  script:
    - docker login -u estore-gitlab-ci -p $CI_TOKEN docker.uibk.ac.at:443
    - docker build -t docker.uibk.ac.at:443/csav4645/sq-estore ./target/*.war
    - docker push docker.uibk.ac.at:443/csav4645/sq-estore