image: maven:3-jdk-8

stages:
  - init
  - build
  - static-analytic
  - test
  
cache:
  paths:
   - ./.m2/repository

variables:
  MYSQL_DATABASE: "estore"
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  MAVEN_OPTS: "-Dmaven.repo.local=./.m2/repository"

mysql-init:
  services:
    - mysql
  image: mysql
  stage: init
  before_script:
    - mysql --version
  script:
    - mysql --host=mysql --user=root "${MYSQL_DATABASE}" < src/test/resources/import.sql

build:
  stage: build
  script:
    - mvn package -DskipTests
  artifacts:
    paths:
      - target/estore*.war

PMD:
  stage: static-analytic
  script:
    - mvn pmd:pmd
    - mvn pmd:cpd

test:
  stage: test
  script:
    - mvn -B install

release:
  stage: deploy
  name: sq-estore Release 1.0
  assets:
    - name: eStore.war
      path: target/estore*.war
    - name: PMD-${APP_VERSION}.xml
      path: target/site/pmd.html
