image: maven:3-jdk-8

variables:
  MYSQL_DATABASE: "estore"
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

services:
  - mysql:latest  

build:
  stage: build
  script:
    - mvn package -DskipTests
  artifacts:
    paths:
      - target/eStore*.jar
#test:
#  stage: test
#  script:
#    - mvn pmd:pmd
#    - mvn pmd:cpd
#    - mvn test

package:
  stage: deploy
  image: docker
  script:
    - docker login -u $CI_REGISTRY_USER -p CI_REGISTRY_PASSWORD docker.uibk.ac.at:443
    - docker build -t docker.uibk.ac.at:443/csav4645/sq-estore ./target/*.war
    - docker push docker.uibk.ac.at:443/csav4645/sq-estore