version: '3'
services:
  eStore-app:
    container_name: eStore-app
    build:
      context: .
      dockerfile: Dockerfile
    image: candirsalih/eStore-app:1.0.0
    restart: on-failure
    depends_on:
      - eStore-Database
    ports:
      - 80:8080
    networks:
      - net-database

  eStore-Database:
    container_name: eStore-Database
    image: mysql:5.6.47
    environment:
      MYSQL_DATABASE: estore
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306:3306
    networks:
      - net-database
    volumes:
      - db-eStore:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

# Store database data
volumes:
  db-eStore:

# Networks
networks:
  net-database: