version: '3'
services:
  database:
    container_name: database
    image: mariadb:10.4.11-bionic
    restart: on-failure
    environment:
      MYSQL_DATABASE: estore
      # create root without password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306:3306
    networks:
      - net-database
    volumes:
      - db-data:/var/lib/mysql

# Store database data
volumes:
  db-data:

# Networks
networks:
  net-database:
