// Generated by GraphWalker (http://www.graphwalker.org)
package eStore;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "eStore/AddToCart.graphml")
public interface AddToCart {

    @Edge()
    void viewProductListPage();

    @Edge()
    void viewCartPage();

    @Vertex()
    void CartPage();

    @Vertex()
    void ProductListPage();

    @Edge()
    void addToCart();

    @Vertex()
    void LoggedIn();

    @Edge()
    void login();

    @Vertex()
    void LoginPage();

    @Vertex()
    void AddedToCart();
}
